### ISSUE TITLE
Homepage: Font-weight for "See what our team..." title was set to 500. It should be regular.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#12]
Screenshot(s):

![homepage - 07](https://cloud.githubusercontent.com/assets/12888048/8514933/c2847c3e-23cb-11e5-92de-1c5be3c0cef0.jpg)

**Comment by arielcebudigital** [comment]
This time I will make this invalid because, it's not all the time the font-weight normal is 400, it depends on the fonts specially if the fonts were generated to webfonts specially using (fontsquirrel.com).

Ex: (generated webfont sample), the font-weight is already normal, so it reflects it corresponding number (300, 400 or 500)

@font-face {
    font-family: 'robotoregular';
    src: url('roboto-regular-webfont.eot');
    src: url('roboto-regular-webfont.eot?#iefix') format('embedded-opentype'),
         url('roboto-regular-webfont.woff2') format('woff2'),
         url('roboto-regular-webfont.woff') format('woff'),
         url('roboto-regular-webfont.ttf') format('truetype'),
         url('roboto-regular-webfont.svg#robotoregular') format('svg');
    font-weight: normal;
    font-style: normal;
}

**Comment by arielcebudigital** [comment]
To make it done, I add font-weight again to normal I hope it will help you next time :-), There are different ways to get the webfonts.

**Comment by romatitan** [comment]
Verified fixed. font-weight: normal;
