### ISSUE TITLE
Form & Checklist: Item(s) should have a pair per each row.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Quest-Taxation#56]
Screenshot(s):
![fc - 04](https://cloud.githubusercontent.com/assets/12888048/8537099/9b33c060-248c-11e5-88a5-46a0a5011c1e.jpg)

**Comment by arielcebudigital** [comment]
For this page the row must not limit, it's up to the client on how many files should he/she uploaded since we used repeater and I already check the project scope they don't mention there that we need to limit, please try to re-check it, If value 1 is missing on the repeater value, frontend view will not show data as it lacks value in backend

**Comment by romatitan** [comment]
I'm not trying to say or to limit the items.
In the above screenshot, we have item "F&C Test d" and "F&C Test e".
The  "F&C Test d" should be placed on the left side and  "F&C Test e" should be placed & aligned opposite to  F&C Test d.

Please check again with this new screenshot.

![fc - 05](https://cloud.githubusercontent.com/assets/12888048/8644498/17f00282-2972-11e5-8c6a-b38f576333f9.jpg)

The screenshot shows, due to the first item long title, item "Test 3c" was placed at the right side opposite to the Test 3a "download" file. 

It should be placed on the left side and "Test 3d" should be its opposite item. 
Making it a pair in a row ( Test 3c ----  Test 3d )

**Comment by romatitan** [comment]
Hi,
Please check again with this new screenshot.

![fc - 07](https://cloud.githubusercontent.com/assets/12888048/8714661/4380f476-2baa-11e5-9830-83b4ac2ae806.jpg)

**Comment by romatitan** [comment]
No fixes for this?
